locale: "en-US"
title: "Martin Haugh"
title_separator: "-"
name: "Martin Haugh"
description: "Associate Professor of Analytics and Operations Research at Imperial Business School"
url: "https://martin-haugh.github.io"
baseurl: ""
repository: "martin-haugh.github.io"
breadcrumbs: false
words_per_minute: 160
future: false
timezone: "America/Los_Angeles"

author:
  name: "Martin Haugh"
  avatar: "Haugh_Martin-Imperial.jpg"
  bio: "Associate Professor of Analytics and Operations Research at Imperial Business School"
  location: "London, U.K."
  googlescholar: "https://scholar.google.com/citations?user=cSXJYiUAAAAJ&hl=en"
  email: "martin.b.haugh@gmail.com"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - _config.dev.yml
  - package.json
  - node_modules
  - tmp
  - vendor
  - log
  - Gemfile
  - Capfile
  - Gruntfile.js
  - Rakefile
  - gulpfile.js
  - config
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor

keep_files:
  - .git
  - .svn

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
